
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]


jobs:
  deploy-frontend:
    runs-on: self-hosted
    steps:
      - name: Clonar repositorio frontend
        uses: actions/checkout@v3
        with:
            path: frontend 

      - name: Configurar Node.js
  
        uses: actions/setup-node@v3
        with:
              node-version: 22.9.0

      # Instalar herramientas globales
      - name: Instalar dependencias globales
        working-directory: ./frontend
        run: |
              npm install -g dotenv-cli
              npm install -g pm2
              
      - name: Instalar y buildear
        working-directory: ./frontend
        run: |
          npm install

      - name: Borrar  frontend
        working-directory: ./frontend
        run: |
           pm2 delete "frontend" || true
      - name: Desplegar frontend
        working-directory: ./frontend
        run: |
           pm2 start npm --name "frontend" -- run pre -- -p 3001
